# Generated by Django 2.2.19 on 2023-01-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230124_1013'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscription_user_author',
        ),
    ]
