# Generated by Django 2.2.19 on 2023-01-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230124_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
